
spring:
  redis-gps:
    database: 2
    host: ${REDIS_HOST:192.168.1.187}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PWD:}
    timeout: 6000ms  # 连接超时时长（毫秒）
    lettuce:
      pool:
        max-idle: 512 #连接池中的最大空闲连接
        min-idle: 0 #连接池中的最小空闲连接
        max-active: 20 #连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 #连接池最大阻塞等待时间（使用负值表示没有限制）
