# Tomcat
server:
  port: 8085
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  servlet:
    context-path: /api
  websocket:
    exporter:
      enable: true

spring:
  # 环境 dev|test|prod
  profiles:
    active: dev
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  mvc:
    throw-exception-if-no-handler-found: true
#  resources:
#    add-mappings: false


#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-handlers-package: com.gps.db.db
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.gps.api.modules.*.entity,com.gps.common.entity
  global-config:
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
#      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
#      field-strategy: NOT_NULL
#      #驼峰下划线转换
#      column-underline: true
      logic-delete-value: -1
      logic-not-delete-value: 0
    banner: false
  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'

gps180:
#  redis:
#    open: false
#  shiro:
#    redis: false
  # APP模块，是通过jwt认证的，如果要使用APP模块，则需要修改【加密秘钥】
  jwt:
    # 加密秘钥
    secret: f4e2e62034348f86b67cde581c0f9eb5[www.gps180.com]
    # token有效时长，7天，单位秒
    expirePhone: 604800
    expireWeb: 43200
    header: token

#配置KAFKA
#============== kafka ===================
kafka:
  consumer:
    servers: ${KAFKA_ADDRESS:192.168.1.187:9092}
    enable:
      auto:
        commit: true
    session:
      timeout: 6000
    auto:
      commit:
        interval: 100
      offset:
        reset: latest
    topic: notifyui
    group:
      id: ${KAFKA_GROUP:consumerForPush}
    concurrency: 10
  producer: #command
    servers: ${KAFKA_ADDRESS:192.168.1.187:9092}
    retries: 0
    security:
      protocol: PLAINTEXT
    batch:
      size: 4096
    linger: 1
    buffer:
      memory: 40960


webSocket:
  heartCheck:
    enabled: true
    timeSpan: 20000
    errorToleration: 3
    trigger: 30 * * * * ?

